### ISSUE TITLE
Administrator adding doctor.

### ISSUE THREAD

**Issue by 707831** [ComputerArcades/HealFolio#14]
We can have example doctors on our database that will be authorized for certain tasks, like viewing certain patient information an being able to log in because of verified practice number. Later on we can link the application to the registered list to verify a doctor.

**Comment by tumbone** [comment]
@metaphizix Let's chat about how I'm adding emails (doctors) to the firebase database for this feature before you start working on it

**Comment by metaphizix** [comment]
Do you mean how are you adding them manually to firebase to test the login function?

**Comment by tumbone** [comment]
@metaphizix  Yeah, should we integrate our system with that somehow or must we create our own authentication?

**Comment by 707831** [comment]
We can have example doctors on our database that will be authorized for certain tasks, like viewing certain patient information an being able to log in because of verified practice number. Later on we can link the application to the registered list to verify a doctor.
